spring:
    datasource:
        initialize: true
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://google/${CLOUD_SQL_DATABASE_NAME:marketplace}?cloudSqlInstance=${DEVSHELL_PROJECT_ID:qwiklabs-gcp-03-c2ba3b787460}:us-central1:mysql-db-container&socketFactory=com.google.cloud.sql.mysql.SocketFactory
        username: ${USER_ID:root}
        password: ${PASSWORD:tpm1234}
        initialization-mode: always
        schema: classpath:/schema.sql
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect